CONSOLE_MODE = t

include cpp/variables.def

PROJECT = example_application
TYPE = application
SOURCE = 
TARGETS = example_application.exe
LOCAL_LIBS_USED = application unit_test loggers configuration processes filesystem textual \
  structures timely basis

include cpp/rules.def

