CONSOLE_MODE = t

include cpp/variables.def

PROJECT = nechung
TYPE = application
SOURCE = nechung_oracle.cpp nechung_version.rc 
DEFINITIONS += __BUILD_STATIC_APPLICATION__
UNDEFINITIONS += ENABLE_MEMORY_HOOK ENABLE_CALLSTACK_TRACKING
TARGETS = nechung.exe cgi_nechung.exe

include cpp/rules.def

