CONSOLE_MODE = true

include cpp/variables.def

PROJECT = app_bundle
TYPE = application
SOURCE = common_bundle.cpp 
ifeq "$(OMIT_VERSIONS)" ""
  SOURCE += bundler_version.rc
endif
DEFINITIONS += __BUILD_STATIC_APPLICATION__=t
TARGETS = bundle_creator.exe

LIBS_USED += z

include cpp/rules.def

