CONSOLE_MODE = true

include cpp/variables.def

PROJECT = app_bundle_stub
TYPE = application
SOURCE = common_bundle.cpp
ifeq "$(OMIT_VERSIONS)" ""
  SOURCE += bundler_version.rc
endif
DEFINITIONS += __BUILD_STATIC_APPLICATION__=t
TARGETS = unpacker_stub.exe

LAST_TARGETS = show_makefilename
OTHER_CLEANS = mocko

LIBS_USED += z

include cpp/rules.def

show_makefilename:
	echo hey the makeflags are $(MAKEFLAGS)


mocko:
	echo got to other cleans

