CONSOLE_MODE = t

include cpp/variables.def

PROJECT = load_test_tools
TYPE = application
SOURCE = 
TARGETS = memory_hog.exe
LOCAL_LIBS_USED = application unit_test loggers configuration processes filesystem textual \
  structures timely basis

include cpp/rules.def

