CONSOLE_MODE = t

include cpp/variables.def

PROJECT = transporter
TYPE = application
SOURCE = transporter_version.rc
TARGETS = find_missing.exe synch_files.exe transporter.exe 
LOCAL_LIBS_USED = application configuration cromp crypto loggers sockets tentacles octopus processes textual timely filesystem nodes structures basis 
USE_SSL = t
VCPP_USE_SOCK = t

include cpp/rules.def

